# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(default='', max_length=32)),
                ('second_name', models.CharField(default='', max_length=32)),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_moder', models.BooleanField(default=False)),
                ('is_clinic', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '������������',
                'verbose_name_plural': '������������',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=6, unique=True, verbose_name='Дом')),
                ('building', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Строение')),
                ('apartments', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Квартира')),
                ('latitude', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Долгота')),
                ('description', models.TextField(max_length=64, verbose_name='Описание')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='place',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Street', verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Place'),
        ),
    ]
